services:
    library-db:
        image: postgres
        command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
        ports:
            - "5432:5432"
        env_file: library_back/.env
        volumes:
            - /var/lib/postgresql/data
        expose:
            - "5432"
    library-back:
        build:
            context: ./library_back
            dockerfile: Dockerfile
        command: bash -c "python library_back/manage.py makemigrations && 
                          python library_back/manage.py migrate && 
                          python library_back/manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/library-back
        depends_on:
            - library-db
    library-front:
        build:
            context: ./library_front/
            dockerfile: Dockerfile
        restart: always
        command : npm start
        ports:
            - "3000:3000"
        stdin_open: true
        depends_on:
            - library-back  
