version: "3.3"
services:
    library-db:
        container_name: library-db
        image: postgres
        command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
        ports:
            - "5432:5432"
        env_file: library_back/.env
        volumes:
            - /var/lib/postgresql/data
        expose:
            - "5432"
    library-back:
        container_name: library-back
        build: ./library_back
        image: library-back
        command: ["sh", "scripts/start.sh"]
        ports:
            - "8000:8000"
        volumes:
            - .:/library-back
        depends_on:
            - library-db
    library-front:
        container_name: library-front
        build: ./library_front
        image: library-front
        restart: always
        command : npm start
        ports:
            - "3000:3000"
        stdin_open: true
        depends_on:
            - library-back
    nginx:
        container_name: library-nginx
        depends_on:
            - library-db
            - library-back
            - library-front
        restart: always
        image: library-nginx
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3001:80"
