services:
    library-db:
        image: postgres
        ports:
            - 5432:5432
        env_file: .env
        volumes:
            - library-pg-data:/var/lib/postgresql/data
volumes:
  library-pg-data: {}
